baseURL = "https://pamperki.me"
languageCode = "en"
title = "Pamperki"
theme = "hugo-nederburg-theme"

disqusShortname = "pamperki"

[params]
  # Unmark to use post folder for images. Default is static folder.
  # usepostimgfolder = true

  # TODO(oxddr): fill it
  slogan = ""
  # TODO(oxddr): fill it
  description = ""
  author = "ddr"
  copyright = [
    "&copy; 2019 oxddr",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
    "A port of Tracks by Compete Themes."
  ]

  [params.social]
  rss = true

  [[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1

[markup.goldmark.renderer]
unsafe= true
